config/routes.rb
Klausur::Application.routes.draw do

  devise_for :users

  root :to => "documents#index"

  resources :documents

  resources :semesters

  resources :doc_types

  resources :lessons

  resources :profs

end

app/controllers/doc_types_controller.rb
class DocTypesController < ApplicationController
  before_filter :authenticate_user!, :only => [:destroy, :edit ]
  # GET /doc_types
  # GET /doc_types.json
  def index
    @doc_types = DocType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @doc_types }
    end
  end

  # GET /doc_types/1
  # GET /doc_types/1.json
  def show
    @doc_type = DocType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @doc_type }
    end
  end

  # GET /doc_types/new
  # GET /doc_types/new.json
  def new
    @doc_type = DocType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @doc_type }
    end
  end

  # GET /doc_types/1/edit
  def edit
    @doc_type = DocType.find(params[:id])
  end

  # POST /doc_types
  # POST /doc_types.json
  def create
    @doc_type = DocType.new(params[:doc_type])

    respond_to do |format|
      if @doc_type.save
        format.html { redirect_to @doc_type, notice: 'Doc type was successfully created.' }
        format.json { render json: @doc_type, status: :created, location: @doc_type }
      else
        format.html { render action: "new" }
        format.json { render json: @doc_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /doc_types/1
  # PUT /doc_types/1.json
  def update
    @doc_type = DocType.find(params[:id])

    respond_to do |format|
      if @doc_type.update_attributes(params[:doc_type])
        format.html { redirect_to @doc_type, notice: 'Doc type was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @doc_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doc_types/1
  # DELETE /doc_types/1.json
  def destroy
    @doc_type = DocType.find(params[:id])
    @doc_type.destroy

    respond_to do |format|
      format.html { redirect_to doc_types_url }
      format.json { head :ok }
    end
  end
end

app/helpers/doc_types_helper.rb
module DocTypesHelper
end

app/views/doc_types/_form.html.erb
<%= form_for(@doc_type) do |f| %>
  <% if @doc_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doc_type.errors.count, "error") %> prohibited this doc_type from being saved:</h2>

      <ul>
      <% @doc_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/doc_types/edit.html.erb
<h3>Editing doctype</h3>

<%= render 'form' %>

<%= link_to 'show', @doc_type %> |
<%= link_to 'back', doc_types_path %>

app/views/doc_types/index.html.erb
<h3>Listing doctypes</h3>

<table>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @doc_types.each do |doc_type| %>
  <tr>
    <td><%= doc_type.id %></td>
    <td><%= doc_type.name %></td>
    <td><%= link_to 'show', doc_type %></td>
    <td><%= link_to 'edit', edit_doc_type_path(doc_type) %></td>
    <td><%= link_to 'destroy', doc_type, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'new doctype', new_doc_type_path %>

app/views/doc_types/new.html.erb
<h3>New doctype</h3>

<%= render 'form' %>

<%= link_to 'back', doc_types_path %>

app/views/doc_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @doc_type.id %>
</p>

<p>
  <b>Name:</b>
  <%= @doc_type.name %>
</p>


<%= link_to 'edit', edit_doc_type_path(@doc_type) %> |
<%= link_to 'back', doc_types_path %>