config/routes.rb
Klausur::Application.routes.draw do

  devise_for :users

  root :to => "documents#index"

  resources :documents

  resources :semesters

  resources :doc_types

  resources :lessons

  resources :profs

end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :lesson
  belongs_to :semester
  belongs_to :prof
  belongs_to :doc_type
  mount_uploader :file, FileUploader
  
	validates :lesson, :presence => true
	validates :semester, :presence => true
	validates :prof, :presence => true
	validates :doc_type, :presence => true
  validates :file, :presence => true
	def before_update      
		self.file_url = Path.combine($newPath, $newFile)
	end

    def self.filter(params)

        condition ={}
        condition[:prof_id] = params[:prof_id] if params[:prof_id]
        condition[:lesson_id] = params[:lesson_id] if params[:lesson_id]
        condition[:doc_type_id] = params[:doc_type_id] if params[:doc_type_id]
        condition[:semester_id] = params[:semester_id] if params[:semester_id]
        condition.each_pair { |key,value| condition.delete key if value == "" }

        documents = where condition

        documents
    end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
before_filter :authenticate_user!, :only => [:destroy, :edit ]

  # GET /documents
  # GET /documents.json
  def index
    params.delete :utf8
    @documents = Document.filter(params)
    #@documents = Document.all
	
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @documents }
    end
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
    @document = Document.find(params[:id])
	
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @document }
    end
  end

  # GET /documents/new
  # GET /documents/new.json
  def new
    @document = Document.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @document }
    end
  end

  # GET /documents/1/edit
  def edit
    @document = Document.find(params[:id])
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(params[:document])

    #lessons semester prof doc_type
    i = Document.where("lesson_id = ? AND semester_id = ? AND prof_id = ? AND doc_type_id = ?", @document.lesson.id, @document.semester.id, @document.prof.id, @document.doc_type.id).size
    
    #name = docType_prof_fach_sem_zahl
	@document.name = (@document.doc_type.name+'_'+@document.prof.name+'_'+@document.lesson.name+'_'+@document.semester.name+'_'+i.to_s).parameterize
	$upName = @document.name
	
    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render json: @document, status: :created, location: @document }
      else
        format.html { render action: "new" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /documents/1
  # PUT /documents/1.json
  def update
    @document = Document.find(params[:id])
	
	@tmp = Document.new(params[:document])
	
	tmp2 = @document.name
	tempPath = "public/dokumente/"
	extName = File.extname(@document.file_url)
	
	i = Document.where("lesson_id = ? AND semester_id = ? AND prof_id = ? AND doc_type_id = ?", @tmp.lesson.id, @tmp.semester.id, @tmp.prof.id, @tmp.doc_type.id).size
    
    #name = docType_prof_fach_sem_zahl
	@document.name = (@tmp.doc_type.name+'_'+@tmp.prof.name+'_'+@tmp.lesson.name+'_'+@tmp.semester.name+'_'+i.to_s).parameterize
	
	$newPath = tempPath
	$newFile = @document.name+extName
	
	File.rename(tempPath+tmp2+extName, tempPath+@document.name+extName)

    respond_to do |format|
      if @document.update_attributes(params[:document])
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
    @tmp.destroy
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document = Document.find(params[:id])
    @document.destroy

    respond_to do |format|
      format.html { redirect_to documents_url }
      format.json { head :ok }
    end
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= form_for(@document) do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :prof %><br />
    <%= f.select :prof_id, Prof.all.collect { |p| [ p.name, p.id ] } %>
  </div>
  <div class="field">
    <%= f.label :lesson %><br />
	<%= f.select :lesson_id, Lesson.all.collect { |p| [ p.name, p.id ] } %>
  </div>
  <div class="field">
    <%= f.label :semester %><br />
	<%= f.select :semester_id, Semester.all.collect { |p| [ p.name, p.id ] } %>
  </div>
  <div class="field">
    <%= f.label :doc_type %><br />
    <%= f.select :doc_type_id, DocType.all.collect { |p| [ p.name, p.id ] } %>
  </div><br/>
  <div>
    <%= f.file_field :file %>
  </div>
  <div>
    <%= f.label :remote_file_url, "or file http://url" %><br />
    <%= f.text_field :remote_file_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h3>Editing document</h3>
<%= render 'form' %>

<%= link_to 'show', @document %> |
<%= link_to 'back', documents_path %>

app/views/documents/index.html.erb
<h3>Listing documents</h3>

<div id="filter">
    <%= form_tag documents_path, :method => 'get' do %>
        <%= label_tag :prof %>
        <%= collection_select(nil, :prof_id, Prof.all.sort_by {|prof| prof.name}, :id, :name, { :include_blank => true,:selected => params[:prof_id] })  %>
        <%= label_tag :lesson %>
        <%= collection_select(nil, :lesson_id, Lesson.all.sort_by {|lesson| lesson.name}, :id, :name, { :include_blank => true,:selected => params[:lesson_id] })  %>        
        <%= label_tag :semester %>
        <%= collection_select(nil, :semester_id, Semester.all.sort_by {|semester| semester.name}, :id, :name, { :include_blank => true,:selected => params[:semester_id] })  %>
        <%= label_tag :doc_type %>
        <%= collection_select(nil, :doc_type_id, DocType.all.sort_by {|doc_type| doc_type.name}, :id, :name, { :include_blank => true,:selected => params[:doc_type_id] })  %>        
        <%= submit_tag "Filter", :name => nil %>
    <% end %>
</div>



<table width="100%">
  <tr>
    <!--<th>Id</th>
    <th>Name</th>-->
    <th>Professor</th>
    <th>Lesson</th>
    <th>Semester</th>
    <th>Doc type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @documents.each do |document| %>
	  <tr class="<%= cycle("even", "odd") %>">
		<!--<td><%= document.id %></td>
		<td><%= document.name %></td>-->
		<td><%= document.prof.name %></td>
		<td><%= document.lesson.name %></td>
		<td><%= document.semester.name %></td>
		<td><%= document.doc_type.name %></td>
		<td><%= link_to "download " + document.name, "dokumente/" + document.name + File.extname(document.file_url) %></td>
		<td><%= link_to 'show', document %></td>
		<% if user_signed_in? %>
		<td><%= link_to 'edit', edit_document_path(document) %></td>
		<td><%= link_to 'destroy', document, confirm: 'Are you sure?', method: :delete %></td>
		<% end %>
  </tr>
<% end %>
</table>

<br />

<!--<%= link_to 'New Document', new_document_path %>-->

app/views/documents/new.html.erb
<h3>New document</h3>

<%= render 'form' %>

<%= link_to 'back', documents_path %>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @document.id %>
</p>

<p>
  <b>Name:</b>
  <%= @document.name %>
</p>

<p>
  <b>Lesson:</b>
  <%= @document.lesson.name %>
</p>

<p>
  <b>Semester:</b>
  <%= @document.semester.name %>
</p>

<p>
  <b>Prof:</b>
  <%= @document.prof.name %>
</p>

<p>
  <b>Doctype:</b>
  <%= @document.doc_type.name %>
</p>

<% if user_signed_in? %>
	<%= link_to 'edit', edit_document_path(@document) %> |
<% end %>

<%= link_to 'back', documents_path %>