config/routes.rb
Klausur::Application.routes.draw do

  devise_for :users

  root :to => "documents#index"

  resources :documents

  resources :semesters

  resources :doc_types

  resources :lessons

  resources :profs

end

app/models/prof.rb
class Prof < ActiveRecord::Base
  has_many :documents
end

app/controllers/profs_controller.rb
class ProfsController < ApplicationController
  before_filter :authenticate_user!, :only => [:destroy, :edit ]
  # GET /profs
  # GET /profs.json
  def index
    @profs = Prof.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @profs }
    end
  end

  # GET /profs/1
  # GET /profs/1.json
  def show
    @prof = Prof.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @prof }
    end
  end

  # GET /profs/new
  # GET /profs/new.json
  def new
    @prof = Prof.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @prof }
    end
  end

  # GET /profs/1/edit
  def edit
    @prof = Prof.find(params[:id])
  end

  # POST /profs
  # POST /profs.json
  def create
    @prof = Prof.new(params[:prof])

    respond_to do |format|
      if @prof.save
        format.html { redirect_to @prof, notice: 'Prof was successfully created.' }
        format.json { render json: @prof, status: :created, location: @prof }
      else
        format.html { render action: "new" }
        format.json { render json: @prof.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /profs/1
  # PUT /profs/1.json
  def update
    @prof = Prof.find(params[:id])

    respond_to do |format|
      if @prof.update_attributes(params[:prof])
        format.html { redirect_to @prof, notice: 'Prof was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @prof.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profs/1
  # DELETE /profs/1.json
  def destroy
    @prof = Prof.find(params[:id])
    @prof.destroy

    respond_to do |format|
      format.html { redirect_to profs_url }
      format.json { head :ok }
    end
  end
end

app/helpers/profs_helper.rb
module ProfsHelper
end

app/views/profs/_form.html.erb
<%= form_for(@prof) do |f| %>
  <% if @prof.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prof.errors.count, "error") %> prohibited this prof from being saved:</h2>

      <ul>
      <% @prof.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profs/edit.html.erb
<h3>Editing professor</h3>

<%= render 'form' %>

<%= link_to 'show', @prof %> |
<%= link_to 'back', profs_path %>

app/views/profs/index.html.erb
<h3>Listing professors</h3>

<table>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @profs.each do |prof| %>
  <tr>
    <td><%= prof.id %></td>
    <td><%= prof.name %></td>
    <td><%= link_to 'show', prof %></td>
    <td><%= link_to 'edit', edit_prof_path(prof) %></td>
    <td><%= link_to 'destroy', prof, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'new professor', new_prof_path %>

app/views/profs/new.html.erb
<h3>New professor</h3>

<%= render 'form' %>

<%= link_to 'back', profs_path %>

app/views/profs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @prof.id %>
</p>

<p>
  <b>Name:</b>
  <%= @prof.name %>
</p>


<%= link_to 'edit', edit_prof_path(@prof) %> |
<%= link_to 'back', profs_path %>