config/routes.rb
Klausur::Application.routes.draw do

  devise_for :users

  root :to => "documents#index"

  resources :documents

  resources :semesters

  resources :doc_types

  resources :lessons

  resources :profs

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Klausurverwaltung FSMNI</title>
		<%= stylesheet_link_tag    "application" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
		<meta charset="UTF-8" />
	</head>
	<body>

		<header>
			<h1>Fachschaft MNI</h1>
			<h2>Dokumentenverwaltung</h2>
		</header>
		
		<nav>
			<%= link_to 'Documents', documents_path %> ||
            <%= link_to 'New document', new_document_path %> |
            <%= link_to 'New professor', new_prof_path %> |
            <%= link_to 'New lesson', new_lesson_path %> |
            <%= link_to 'New semester', new_semester_path %> |
            <%= link_to 'New doctype', new_doc_type_path %> ||
			
			<% unless user_signed_in? %>
				<%= link_to "Login", new_user_session_path %>
			<% else %>
				<%= link_to "Logout", destroy_user_session_path, :method => :delete %>
			<% end %>
		</nav>
		
		<%= yield %>

		<footer>
			<p>
			<%= link_to 'Professors', profs_path %> |
			<%= link_to 'Lessons', lessons_path %> |
			<%= link_to 'Semesters', semesters_path %> |
			<%= link_to 'Doctypes', doc_types_path %><br/>
			CC BY-NC-SA - Fachschaft MNI - Technische Hochschule Mittelhessen
			</p>

		</footer>
			<img class="logo" src="../../assets/QR-FS-Logo_-_fsmni.thm.de.png" alt="FSMNI Logo" />
			<div class="stats">
				Documents: <%= Document.where('id').size.to_s %><br/>
				<p class="notice"><%= notice %></p>
				<p class="alert"><%= alert %></p>
			</div>
	</body>
</html>